baseURL = 'https://patrider64.github.io/PortFolioHugoDemo/'
languageCode = 'fr-fr'
title = 'Mon Portfolio'
theme = 'ananke'
description = 'Un portfolio et mon premier projet Hugo.'
showReadingTime = true